// src/components/TaskCard.svelte
<script>
	export let cardProps;
	export let taskData;
	export let dateMessage;
	export let styleClass;

	function deleteTask(taskId) {
		console.log(taskId);
	}
</script>

<main>
	<div class="card task-card">
		<div class="card-content">
			<div class="level">
				<div class="level-left">
					<div class="level-item">
						<p class="subtitle is-6 tag {cardProps.tagClassName}">
							{taskData.status === 'inProgress'
								? taskData.status.split('P').join(' p')
								: taskData.status}
						</p>
					</div>
				</div>
				<div class="level-right">
					<div class="level-item">
						{#if taskData.setDeadline}
							<span class="deadline {styleClass}">
								<i class="fa-regular fa-clock" />
								{dateMessage}
							</span>
						{/if}
					</div>
				</div>
			</div>
			<p class="title">{taskData.name}</p>
			<div class="content">
				{taskData.description}
			</div>
		</div>
		<div class="card-footer">
			<button
				class="button is-danger is-light delete-task card-footer-item"
				on:click={deleteTask(taskData.id)}
			>
				Delete
			</button>
			{#if cardProps.btn}
				<button class="${cardProps.btnClassName} button is-info is-light card-footer-item">
					{cardProps.btn}
				</button>
			{/if}
		</div>
	</div>
</main>

// src/app/components/task-card/task-card.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { taskTypes } from 'src/app/shared/configs/constants';
import { TaskMetaData } from 'src/app/shared/models/TaskMetaData';
import { FirestoreService } from 'src/app/shared/services/firestore.service';

@Component({
    selector: 'app-task-card',
    templateUrl: './task-card.component.html',
    styleUrls: ['./task-card.component.scss'],
})
export class TaskCardComponent implements OnInit {
    @Input() task: any;

    @Output() deletedTaskMetaData: EventEmitter<TaskMetaData> =
        new EventEmitter();
    @Output() transistionTaskMetaData: EventEmitter<TaskMetaData> =
        new EventEmitter();

    styleClass: string = '';
    tagClassName: string = '';
    dateMessage: string = '';
    buttonName: string = '';

    constructor(private afs: FirestoreService) {}

    private setTaskConfig() {
        if (this.task?.status === taskTypes.TODO_TYPE) {
            this.tagClassName = 'is-warning';
            this.buttonName = 'Mark in progress';
        } else if (this.task?.status === taskTypes.INPROGRESS_TYPE) {
            this.tagClassName = 'is-info';
            this.buttonName = 'Mark completed';
        } else if (this.task?.status === taskTypes.COMPLETED_TYPE) {
            this.tagClassName = 'is-success';
        }
    }

    ngOnInit(): void {
        this.setTaskConfig();
    }

    async deleteTask(taskId: string, taskType: string) {
        try {
            await this.afs.deleteTaskFromFirestore(taskId);
            this.deletedTaskMetaData.emit({ taskId, taskType });
        } catch (error) {
            console.log(error);
        }
    }

    async transitionTask(taskId: string, taskType: string) {
        try {
            const toTaskType = this.getNewTaskType(taskType);
            await this.afs.updateTaskStatus(taskId, toTaskType);
            this.transistionTaskMetaData.emit({ taskId, taskType, toTaskType });
        } catch (error) {
            console.log(error);
        }
    }

    private getNewTaskType(oldTaskType: string) {
        if (oldTaskType === taskTypes.TODO_TYPE) {
            return taskTypes.INPROGRESS_TYPE;
        }
        return taskTypes.COMPLETED_TYPE;
    }
}

<div class="card task-card">
    <div class="card-content">
        <div class="level">
            <div class="level-left">
                <div class="level-item">
                    <p [ngClass]="'subtitle is-6 tag ' + tagClassName">
                        {{
                            task?.status === 'inProgress'
                                ? task?.status?.split('P')?.join(' p')
                                : task?.status
                        }}
                    </p>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    <span
                        [ngClass]="'deadline ' + styleClass"
                        *ngIf="task?.setDeadline"
                    >
                        <i class="fa-regular fa-clock"></i>
                        {{ dateMessage }}
                    </span>
                </div>
            </div>
        </div>
        <p class="title">{{ task?.name }}</p>
        <div class="content">{{ task?.description }}</div>
    </div>
    <div class="card-footer">
        <button
            class="delete-task card-footer-item"
            (click)="deleteTask(task?.id, task?.status)"
        >
            Delete
        </button>
        <button
            class="card-footer-item"
            *ngIf="task?.status !== 'completed'"
            (click)="transitionTask(task?.id, task?.status)"
        >
            {{ buttonName }}
        </button>
    </div>
</div>
